services:
  n8n:
    build: .
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - VUE_APP_URL_BASE_API=${VUE_APP_URL_BASE_API}
